base = "../base"
includes = [
  ".github/workflows/ci.yaml",
  ".github/dependabot.yaml",
  ".vscode/extensions.json",
  ".vscode/settings.json",
  ".editorconfig",
  ".gitignore",
  "biome.json",
  "tsconfig.json",
]
required = ["LICENSE", "README.md"]
